### PR TITLE
Allow array query params

### LINKED ISSUE #40: Allow positional parameters
For example, we have this query:

```sql
INSERT INTO table VALUES (?, ?, ?)
```

Binding values to those questions marks are not supported by `ws4sqlite` (#39).

I know the documentation wrote that:

> If the query needs to be parametrized, named parameters can be defined in the statement using SQLite (e.g. `:id` or `@id`), and the proper values for them must be specified here.

However, it is a syntax supported by [SQLite itself](https://www.sqlite.org/c3ref/bind_blob.html):

> In the SQL statement text input to [sqlite3_prepare_v2()](https://www.sqlite.org/c3ref/prepare.html) and its variants, literals may be replaced by a [parameter](https://www.sqlite.org/lang_expr.html#varparam) that matches one of following templates:
>
> ```
> ?
> ?NNN
> :VVV
> @VVV
> $VVV 
>```
>
>In the templates above, NNN represents an integer literal, and VVV represents an alphanumeric identifier. The values of these parameters (also called "host parameter names" or "SQL parameters") can be set using the sqlite3_bind_*() routines defined here.

### PR DESCRIPTION
**Pull request by thanhnguyen2187**
Resolve #40.

---

Sample `curl`:

```
curl \
    -X POST \
    --header 'Content-Type: application/json' \
    --data @/tmp/data.json \
    --fail-with-body \
    127.0.0.1:12321/crypta \
| jq
```

Sample body:

```json
{
    "transaction": [
        {
            "statement": "CREATE TABLE table_with_many_columns (d INT, c INT, b INT, a INT)",
            "values": []
        },
        {
            "statement": "INSERT INTO table_with_many_columns VALUES (?, ?, ?, ?)",
            "values": [1, 1, 1, 1]
        },
        {
            "statement": "INSERT INTO table_with_many_columns VALUES (?, ?, ?, ?)",
            "valuesBatch": [
                [2, 2, 2, 2],
                [3, 3, 3, 3],
                [4, 4, 4, 4]
            ]
        },
        {
            "query": "SELECT * FROM table_with_many_columns"
        },
        {
            "statement": "DROP TABLE table_with_many_columns"
        }
    ]
}
```

Sample response:

```json
{
  "results": [
    {
      "success": true,
      "rowsUpdated": 0
    },
    {
      "success": true,
      "rowsUpdated": 1
    },
    {
      "success": true,
      "rowsUpdatedBatch": [
        1,
        1,
        1
      ]
    },
    {
      "success": true,
      "resultSet": [
        {
          "d": 1,
          "c": 1,
          "b": 1,
          "a": 1
        },
        {
          "d": 2,
          "c": 2,
          "b": 2,
          "a": 2
        },
        {
          "d": 3,
          "c": 3,
          "b": 3,
          "a": 3
        },
        {
          "d": 4,
          "c": 4,
          "b": 4,
          "a": 4
        }
      ]
    },
    {
      "success": true,
      "rowsUpdated": 1
    }
  ]
}
```

### CODE REVIEW

**Comment by thanhnguyen2187** [comment]
@proofrock I will rebase this after #38 is merged.

**Comment by proofrock** [comment]
Looks nice, thanks! Yes, let's rebase it after #38

**Comment by proofrock** [comment]
Thanks. There are still a couple of errors and conflicts, would you solve them (whenever you can)? Please try a "make test" afterwards.

```
./web_service.go:66:62: undefined: requestItemCrypto
./web_service.go:311:58: txItem.Decoder undefined (type requestItem has no field or method Decoder)
```

**Comment by proofrock** [comment]
Good code anyway, thanks! 👍

**Comment by thanhnguyen2187** [comment]
Oh yep I'm trying to rebase, but it seems simpler to create a new branch and copy the changes manually anyway :sweat_smile:. I'll let you know when the new branch is ready

**Comment by thanhnguyen2187** [comment]
@proofrock it should be ready

**Comment by proofrock** [comment]
Many thanks!!

**Comment by proofrock** [comment]
Next step is to write documentation for all that, but before I'd like to do the resultset format "change"

**Pull request merged**
