### PR TITLE
Change underlying data structure of `resultSet`

### PR DESCRIPTION
**Pull request by thanhnguyen2187**
From `map[string]interface{}` to `OrderedDict`.

Should serve as a prototype to https://github.com/proofrock/sqliterg/issues/5.

### CODE REVIEW

**Comment by proofrock** [comment]
Thanks, and I mean it!!

While this should not be a problem to merge (no regressions, an ordered map is an unordered map, so to speak), I still feel this is not the right way, because in json a map is unordered. I'd rather implement the solution proposed in the issue discussion, in due time.

Anyway, I'll merge this, first I need to switch from gitflow to trunk-based though; it's something I must do anyway and this PR is against `main`.

Thanks again!

**Comment by thanhnguyen2187** [comment]
Suggestion: you might want to look at this library (https://github.com/stretchr/testify) for assertion, and test suite setting up plus tearing down. I think depending on the way Go collect tests for setting up and tearing down complect the code and debugging :sweat_smile:.

**Comment by proofrock** [comment]
I think it's solid, and thanks. WHat is the reason for `getDefault[...]()`? What makes it necessary?

**Comment by proofrock** [comment]
Tests pass. Thanks, and merging now.

**Comment by proofrock** [comment]
Please notice that after this, I cannot implement the solution for sqliterg#5 anymore, because getDefault "wants" a map. Is getDefault really necessary?

**Comment by thanhnguyen2187** [comment]
`OrderedDict.Get()` returns the value if found and `ok`, which means in a lot of places, I would have to create many temporary variables whenever I invoke `.Get`. I use `getDefault` to reduce the boilerplate in this case. The underlying logic should not matter that much, I think.

**Comment by proofrock** [comment]
I see. What I plan to do is to use a generic `interface{}` to replace with a map or a list as needed; but of course I cannot pass it to `getDefault`. I need to cast it explicitly in the relevant tests, but I would have to do it anyway.

**Comment by proofrock** [comment]
@thanhnguyen2187 

This works fine, but in practice it introduces an inconsistency. The json that it produces is ordered, but when it parses the same json it attempts to parse it unordered.

This is apparent if you substitute `[]interface{}` to `[]orderedmap.OrderedMap`, as type for `ResultSet`; problem is, this is the way I need to implement the "resultset as a list" feature. Depending on the input parameter, I need to populate `ResultSet` with a map or a list.

But then all tests fail, because when it parses the json it parses a `map[string]interface{}`...

What if we maintain the unordered map (as I said, json *is* unordered) and add a list of column headers as an additional response field? You could read the order from this list and get them from the map. And I would do also the resultset-as-list.

This should cover your use case, and it would be more... coherent.

**Comment by proofrock** [comment]
Alternate: since it's not strictly necessary in the tests to have an orderedmap, let it deserialize to `map[string]interface{}` and be done with it, putting a very big comment documenting the inconsistency. To tell the truth, I don't like it too much.

**Pull request merged**
